import { Bar } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

const WasteGenerationChart = () => {
  const data = {
    labels: ['<1 kg', '1–5 kg', '5–10 kg', '10–20 kg', '20kg+'],
    datasets: [{
      label: 'Number of Responses',
      data: [22, 14, 21, 63, 42],
      backgroundColor: [
        '#4f8df7',
        '#37c6eb',
        '#4caf50',
        '#ffb300',
        '#ff5252'
      ],
      borderRadius: 8,
    }]
  };

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      title: {
        display: true,
        text: 'Daily Waste Generated by Respondents',
        font: {
          size: 16,
          weight: 'bold' as const,
        },
        color: '#333',
      },
      tooltip: {
        callbacks: {
          label: (context: any) => `Responses: ${context.raw}`,
        },
      },
    },
    scales: {
      y: {
        beginAtZero: true,
        title: { 
          display: true, 
          text: 'Responses Count',
          font: { size: 14 },
          color: '#333',
        },
        ticks: {
          color: '#333',
          font: { size: 14 },
        },
      },
      x: {
        title: { 
          display: true, 
          text: 'Daily Waste Category',
          font: { size: 14 },
          color: '#333',
        },
        ticks: {
          color: '#333',
          font: { size: 13 },
        },
      },
    },
  };

  return (
    <div className="w-full h-full flex flex-col items-center justify-center p-4 sm:p-6">
      <h3 className="text-xl sm:text-2xl font-semibold text-foreground mb-2 text-center">
        Daily Waste Generated Analysis
      </h3>
      <p className="text-xs sm:text-sm text-muted-foreground mb-6 sm:mb-8 text-center">
        Survey responses (n=162)
      </p>
      
      <div className="w-full max-w-[900px] mx-auto">
        <div className="bg-card rounded-xl shadow-sm p-4 sm:p-6">
          <div className="h-[300px] sm:h-[400px] md:h-[450px]">
            <Bar data={data} options={options} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default WasteGenerationChart;
